import praw
import time
import random

reddit = praw.Reddit(
    client_id='l21MVg2tp7sehA',
    client_secret='IrsBqAAJtm2rdFBB_opJ-PqVq0IE2A',
    user_agent='leesang627_messagebot',
    username='leesang627',
    password='&g*G5hbCb',
    ratelimit_seconds=10,
)

# reddit = praw.Reddit(
#     client_id='tvP60525vaRBhA',
#     client_secret='J4yygRJ5fqlLNNDqwp7P2zDy60sZdw',
#     user_agent='woogler6682_messagebot',
#     username='woogler6682',
#     password='P^#2S3orS!j'
# )

large_subreddit_list_1 = ['natureismetal', 'SkincareAddiction', 'therewasanattempt', 'trashy', 'Rainbow6',
                          'leagueoflegends', 'WatchPeopleDieInside', 'science', 'Unexpected', 'Documentaries', 'math',
                          'UnresolvedMysteries', 'niceguys', 'quityourbullshit', 'pokemongo', 'LegalTeens', 'biology',
                          'loseit', 'instant_regret', 'keto', 'Fitness', 'PUBATTLEGROUNDS', 'HistoryPorn',
                          'MovieDetails',
                          'HumansBeingBros', 'HomeImprovement', 'WTF', 'philosophy', 'raspberry_pi', 'gaming',
                          'comedyheaven', 'NintendoSwitch', 'trees', 'history', 'photoshopbattles', 'atheism', 'nasa',
                          'DunderMifflin', 'PublicFreakout', 'PetiteGoneWild', 'holdmycosmo', 'Eyebleach',
                          'InternetIsBeautiful', 'AmItheAsshole', 'sex', 'insanepeoplefacebook', 'creepy',
                          'listentothis',
                          'food', 'mildlyinfuriating']

large_subreddit_list_2 = ['PerfectTiming', 'wallpaper', 'offmychest', 'assholedesign', '2meirl4meirl',
                          'UnethicalLifeProTips', 'dataisbeautiful', 'nextfuckinglevel', 'lifehacks', 'hearthstone',
                          'FortNiteBR', 'nsfw', 'xboxone', 'MakeupAddiction', 'freefolk', 'programming', 'BeAmazed',
                          'coolguides', 'instantkarma', 'rareinsults', 'dogs', 'reactiongifs', 'nevertellmetheodds',
                          'Futurology', 'legaladvice', 'ShittyLifeProTips', 'WeAreTheMusicMakers',
                          'technicallythetruth', 'GetMotivated', 'MaliciousCompliance', 'YouShouldKnow', 'crafts',
                          'holdmybeer', 'pcgaming', 'AnimalsBeingBros', 'AnimalsBeingDerps', 'wow', 'tifu',
                          'askscience', 'streetwear', 'UpliftingNews', 'NatureIsFuckingLit', 'iamverysmart',
                          'Cinemagraphs', 'TrollYChromosome', 'dating_advice', 'ATBGE', 'blog', 'writing', 'technology']

middle_subreddit_list_1 = ['forcedcreampie', 'beerporn', 'indianpeoplefacebook', 'ImaginaryTechnology',
                           'talesfromtechsupport', 'ItemShop', 'MkeBucks', 'Pegging', 'Marvel', 'virginvschad',
                           'WhyWereTheyFilming', 'holdmyfeedingtube', 'shortcuts', 'catsareliquid', 'LetsTalkMusic',
                           'blunderyears', 'datgap', 'CatsISUOTTATFO', 'AdrianaChechik', 'ireland', 'islam', 'pornvids',
                           'youdontsurf', 'orgasmiccontractions', 'germany', 'phgonewild', 'China_Flu', 'TheWayWeWere',
                           'marijuanaenthusiasts', 'NeckbeardNests', 'slammywhammies', 'smallboobs', 'The_Mueller',
                           'holdmyjuicebox', 'Undertale', 'de_IAmA', 'raining', 'MyPeopleNeedMe', 'PUBG', 'howyoudoin',
                           'Justfuckmyshitup', 'GlobalOffensiveTrade', 'Cuckold', 'YouSeeComrade', 'Monero',
                           'assassinscreed', 'datascience', 'TinyTits', 'philadelphia', 'trashpandas',
                           'dogquest', 'MadeChina', 'SkyClan', 'HumansBeingAnimals', 'ObscureFilmClub',
                           'winkhub', 'cssroztest', 'Have_Fun', 'LethalLeagueLadder',
                           'im3', 'Gereshes', 'trolling_Jagex',
                           'fallout_neworleans', 'ChanelNoir', 'TheFarmingGame', 'buddhistcults', 'Caughtnaked',
                           'Clickwise', 'Estrangedstuff', 'DerHofer', 'cosplaycup', 'diepFlairTesting', 'DrugSynthesis',
                           'ABLaw', 'FoxPrivate', 'PharmacyResidency', 'sexyvixens', 'IconJar', 'Su_tart', 'CuntClub',
                           'LSML', 'sludgezone', 'behavioural_analytics', 'CapitalistVictims', 'gametokers',
                           'LyricInterpretation', 'yankjauhyayank', 'rslashwooshr', 'yeahrightman', 'Gorepics',
                           'newgamemusic', 'ESPN_NEWS', 'requelmemes']

subject = 'Looking for Reddit moderators to participate in an online user study'
content = '''Hi r/{} moderators, We are a group of online community researchers at DGIST([https://dgist.ac.kr/en/](https://dgist.ac.kr/en/)) and KAIST([https://www.kaist.ac.kr/](https://www.kaist.ac.kr/)), South Korea.

*First, we are sorry for spamming a recruitment flyer through modmail. If you are not interested, please ignore this message.*

We are looking for **Reddit moderators** who can participate in an **online user study** to test our built AutoMod Sandbox Tool.
Your participation can help us **improve the Reddit moderator's user experience about AutoMod configuration**. 

We are conducting the online user study with a prototype tool we built to overcome challenges with testing AutoMod configurations. We would really appreciate your participation in our study to use our prototype tool and answer questions related to its usability. 
The study will take approximately **2 hours** to complete with a reward of **$20/hr**. If it takes longer, we will pay for the exceeded time. This reward takes into account the labor of the tasks you participate in, not your status as a Reddit moderator.

**Procedure and Time**
1. Orientation (5 min)
2. Learning how to write AutoMod rules (10 min)
3. Two Main Tasks (60-80 min)
4. Post Survey (5 min)
5. Interview (10 min)

**Two Main tasks**
- We give example posts and moderation objectives for each task.
- You need to create and update your own AutoMod rules using given tools.
- You need to think-aloud what you are thinking during the task so that we can understand how you are using our tools and what kind of questions you have with using it. 

The whole session will be **recorded** (with the camera turn off), but only for research purposes and will not be shared with anyone besides the team, and will be discarded right after the research. You can participate **until 9/1**. 

Please sign up at [https://forms.gle/kxoRjNkeoKjcg3eP9](https://forms.gle/kxoRjNkeoKjcg3eP9) if you are interested!

If you have any questions, please feel free to contact us: Jean Young Song: jeansong@dgist.ac.kr

We uploaded information about our project and Reddit username to the lab website temporarily to prove our identity. [https://www.kixlab.org/projects](https://www.kixlab.org/projects)
you can find the link to this lab website on the official KAIST CS website. [https://cs.kaist.ac.kr/research/interaccom](https://cs.kaist.ac.kr/research/interaccom)

Thank you!
'''

list_of_subreddits = ['ListOfSubreddits.', 'gifs', 'behindthegifs', 'gif', 'Cinemagraphs', 'WastedGifs',
                      'educationalgifs', 'perfectloops', 'highqualitygifs', 'gifsound', 'combinedgifs', 'retiredgif',
                      'michaelbaygifs', 'gifrecipes', 'mechanical_gifs', 'bettereveryloop', 'gifextra', 'slygifs',
                      'gifsthatkeepongiving', 'wholesomegifs', 'noisygifs', 'brokengifs', 'loadingicon',
                      'splitdepthgifs', 'blackpeoplegifs', 'whitepeoplegifs', 'asianpeoplegifs', 'scriptedasiangifs',
                      'reactiongifs', 'shittyreactiongifs', 'chemicalreactiongifs', 'physicsgifs', 'babyelephantgifs',
                      'weathergifs', 'pics', 'PhotoshopBattles', 'perfecttiming', 'itookapicture', 'Pareidolia',
                      'ExpectationVSReality', 'dogpictures', 'misleadingthumbnails', 'FifthWorldPics', 'TheWayWeWere',
                      'pic', 'nocontextpics', 'miniworlds', 'foundpaper', 'images', 'screenshots', 'mildlyinteresting',
                      'interestingasfuck', 'damnthatsinteresting', 'beamazed', 'reallifeshinies', 'thatsinsane',
                      'playitagainsam', 'gentlemanboners', 'prettygirls', 'hardbodies', 'girlsmirin', 'thinspo',
                      'goddesses', 'shorthairedhotties', 'fitandnatural', 'wrestlewiththeplot', 'skinnywithabs', 'bois',
                      'GentlemanBonersGifs', 'asiancuties', 'asiangirlsbeingcute', 'PhotoshopBattles',
                      'ColorizedHistory', 'reallifedoodles', 'HybridAnimals', 'colorization', 'amiugly', 'roastme',
                      'rateme', 'uglyduckling', 'prettygirlsuglyfaces', 'wallpapers', 'wallpaper',
                      'Offensive_Wallpapers', 'videos', 'youtubehaiku', 'artisanvideos', 'DeepIntoYouTube',
                      'nottimanderic', 'praisethecameraman', 'killthecameraman', 'perfectlycutscreams',
                      'donthelpjustfilm', 'abruptchaos', 'ShowerThoughts', 'DoesAnybodyElse', 'changemyview',
                      'crazyideas', 'howtonotgiveafuck', 'tipofmytongue', 'quotes', 'casualconversation',
                      'makenewfriendshere', 'relationship_advice', 'raisedbynarcissists', 'legaladvice', 'advice',
                      'amitheasshole', 'mechanicadvice', 'toastme', 'needadvice', 'IAmA', 'ExplainlikeIAmA', 'AMA',
                      'casualiama', 'de_Iama', 'whowouldwin', 'wouldyourather', 'scenesfromahat', 'AskOuija',
                      'themonkeyspaw', 'shittysuperpowers', 'godtiersuperpowers', 'decreasinglyverbose',
                      'jesuschristouija', 'whatisthisthing', 'answers', 'NoStupidQuestions', 'amiugly', 'whatsthisbug',
                      'samplesize', 'tooafraidtoask', 'whatsthisplant', 'isitbullshit', 'morbidquestions', 'AskReddit',
                      'ShittyAskScience', 'TrueAskReddit', 'AskScienceFiction', 'AskOuija', 'AskScience',
                      'askhistorians', 'askculinary', 'AskSocialScience', 'askengineers', 'askphilosophy', 'askdocs',
                      'askwomen', 'askmen', 'askgaybros', 'askredditafterdark', 'asktransgender', 'askmenover30',
                      'tifu', 'self', 'confession', 'fatpeoplestories', 'confessions', 'storiesaboutkevin',
                      'talesfromtechsupport', 'talesfromretail', 'techsupportmacgyver', 'idontworkherelady',
                      'TalesFromYourServer', 'KitchenConfidential', 'TalesFromThePizzaGuy', 'TalesFromTheFrontDesk',
                      'talesfromthecustomer', 'talesfromcallcenters', 'talesfromthesquadcar', 'talesfromthepharmacy',
                      'starbucks', 'pettyrevenge', 'prorevenge', 'nuclearrevenge', 'nosleep', 'LetsNotMeet',
                      'Glitch_in_the_Matrix', 'shortscarystories', 'thetruthishere', 'UnresolvedMysteries',
                      'UnsolvedMysteries', 'depression', 'SuicideWatch', 'Anxiety', 'foreveralone', 'offmychest',
                      'socialanxiety', 'trueoffmychest', 'unsentletters', 'rant', 'YouShouldKnow', 'everymanshouldknow',
                      'LearnUselessTalents', 'changemyview', 'howto', 'Foodforthought', 'educationalgifs', 'lectures',
                      'education', 'college', 'GetStudying', 'teachers', 'watchandlearn', 'bulletjournal',
                      'applyingtocollege', 'lawschool', 'todayilearned', 'wikipedia', 'OutOfTheLoop', 'IWantToLearn',
                      'explainlikeimfive', 'explainlikeIAmA', 'ExplainLikeImCalvin', 'anthropology', 'Art',
                      'redditgetsdrawn', 'heavymind', 'drawing', 'graffiti', 'retrofuturism', 'sketchdaily', 'ArtPorn',
                      'pixelart', 'artfundamentals', 'learnart', 'specart', 'animation', 'wimmelbilder', 'illustration',
                      'streetart', 'place', 'breadstapledtotrees', 'chairsunderwater', 'painting', 'minipainting',
                      'gamedev', 'engineering', 'ubuntu', 'cscareerquestions', 'EngineeringStudents', 'askengineers',
                      'learnprogramming', 'compsci', 'java', 'javascript', 'coding', 'machinelearning', 'howtohack',
                      'cpp', 'artificial', 'python', 'learnpython', 'Economics', 'business', 'entrepreneur',
                      'marketing', 'BasicIncome', 'business', 'smallbusiness', 'stocks', 'wallstreetbets',
                      'stockmarket', 'environment', 'zerowaste', 'historynetwork!', 'history', 'AskHistorians',
                      'ColorizedHistory', 'badhistory', '100yearsago', 'HistoryPorn', 'PropagandaPosters',
                      'TheWayWeWere', 'historymemes', 'castles', 'linguistics', 'languagelearning', 'learnjapanese',
                      'french', 'etymology', 'law', 'math', 'theydidthemath', 'medicalschool', 'medizzy', 'psychology',
                      'Science', 'AskScience', 'cogsci', 'medicine', 'everythingscience', 'geology', 'Space',
                      'SpacePorn', 'astronomy', 'astrophotography', 'aliens', 'rockets', 'spacex', 'nasa', 'biology',
                      'Awwducational', 'chemicalreactiongifs', 'chemistry', 'physics', 'entertainment', 'fantheories',
                      'Disney', 'obscuremedia', 'anime', 'manga', 'anime_irl', 'awwnime', 'TsundereSharks',
                      'animesuggest', 'animemes', 'animegifs', 'animewallpaper', 'wholesomeanimemes', 'pokemon',
                      'onepiece', 'naruto', 'dbz', 'onepunchman', 'ShingekiNoKyojin', 'yugioh', 'BokuNoHeroAcademia',
                      'DDLC', 'berserk', 'hunterxhunter', 'tokyoghoul', 'shitpostcrusaders', 'Books', 'WritingPrompts',
                      'writing', 'literature', 'booksuggestions', 'lifeofnorman', 'poetry', 'screenwriting',
                      'freeEbooks', 'boottoobig', 'hfy', 'suggestmeabook', 'lovecraft', 'comics', 'comicbooks',
                      'polandball', 'marvel', 'webcomics', 'bertstrips', 'marvelstudios', 'defenders', 'marvelmemes',
                      'avengers', 'harrypotter', 'batman', 'calvinandhobbes', 'xkcd', 'DCComics', 'arrow',
                      'unexpectedhogwarts', 'spiderman', 'deadpool', 'KingkillerChronicle', 'asoiaf', 'gameofthrones',
                      'freefolk', 'jonwinsthethrone', 'gameofthronesmemes', 'daeneryswinsthethrone',
                      'asongofmemesandrage', 'lotr', 'lotrmemes', 'tolkienfans', 'celebs', 'celebhub', 'EmmaWatson',
                      'jessicanigri', 'kateupton', 'alisonbrie', 'EmilyRatajkowski', 'jenniferlawrence',
                      'alexandradaddario', 'onetruegod', 'joerogan', 'keanubeingawesome', 'crewscrew', 'donaldglover',
                      'elonmusk', 'cosplay', 'cosplaygirls', 'lego', 'boardgames', 'rpg', 'chess', 'poker', 'jrpg',
                      'DnD', 'DnDGreentext', 'DnDBehindTheScreen', 'dndnext', 'dungeonsanddragons', 'criticalrole',
                      'DMAcademy', 'dndmemes', 'magicTCG', 'modernmagic', 'magicarena', 'zombies', 'cyberpunk',
                      'fantasy', 'scifi', 'starwars', 'startrek', 'asksciencefiction', 'prequelmemes',
                      'empiredidnothingwrong', 'SequelMemes', 'sciencefiction', 'InternetIsBeautiful', 'facepalm',
                      'wikipedia', 'creepyPMs', 'web_design', 'google', 'KenM', 'bannedfromclubpenguin',
                      'savedyouaclick', 'bestofworldstar', 'discordapp', 'snaplenses', 'tronix', 'instagramreality',
                      'internetstars', 'robinhood', 'shortcuts', 'scams', 'tiktokcringe', 'crackheadcraigslist',
                      '4chan', 'Classic4chan', 'greentext', 'facepalm', 'oldpeoplefacebook', 'facebookwins',
                      'indianpeoplefacebook', 'terriblefacebookmemes', 'insanepeoplefacebook', 'Tinder', 'OkCupid',
                      'KotakuInAction', 'wikileaks', 'shitcosmosays', 'twitch', 'livestreamfail', 'serialpodcast',
                      'podcasts', 'tumblrinaction', 'tumblr', 'blackpeopletwitter', 'scottishpeopletwitter',
                      'WhitePeopleTwitter', 'wholesomebpt', 'latinopeopletwitter', 'YoutubeHaiku', 'youtube',
                      'youngpeopleyoutube', 'gamegrumps', 'h3h3productions', 'CGPGrey', 'yogscast', 'jontron',
                      'Idubbbz', 'defranco', 'cynicalbrit', 'pyrocynical', 'SovietWomble', 'RedLetterMedia',
                      'videogamedunkey', 'loltyler1', 'ksi', 'MiniLadd', 'jacksepticeye', 'pewdiepiesubmissions',
                      'pewdiepie', 'roosterteeth', 'funhaus', 'rwby', 'cowchop', 'movies', 'documentaries',
                      'fullmoviesonyoutube', 'truefilm', 'bollywoodrealism', 'moviedetails', 'moviesinthemaking',
                      'fullmoviesonvimeo', 'continuityporn', 'ghibli', 'cinematography', 'shittymoviedetails',
                      'moviescirclejerk', 'starwars', 'harrypotter', 'lotr', 'lotrmemes', 'otmemes', 'marvelstudios',
                      'batman', 'DC_Cinematic', 'thanosdidnothingwrong', 'inthesoulstone',
                      'listentothis/about/sidebar\\)', 'music', 'listentothis', 'WeAreTheMusicMakers', 'mashups',
                      'vinyl', 'futurebeats', 'musictheory', 'guitarlessons', 'spotify', 'fakealbumcovers', 'ableton',
                      'kanye', 'radiohead', 'KendrickLamar', 'gorillaz', 'frankocean', 'donaldglover', 'eminem',
                      'brockhampton', 'beatles', 'deathgrips', 'pinkfloyd', 'classicalmusic', 'jazz', 'trap',
                      'indieheads', 'gamemusic', 'outrun', 'vaporwave', 'dubstep', 'electronicmusic', 'edmproduction',
                      'EDM', 'hiphopheads', 'hiphopimages', 'Metal', 'Metalcore', 'spop', 'kpop', 'funkopop',
                      'popheads', 'guitar', 'piano', 'bass', 'drums', 'sports', 'running', 'bicycling', 'golf',
                      'fishing', 'skiing', 'sportsarefun', 'tennis', 'rugbyunion', 'discgolf', 'cricket', 'sailing',
                      'nfl', 'CFB', 'fantasyfootball', 'nflstreams', 'patriots', 'eagles', 'greenbaypackers',
                      'minnesotavikings', 'losangelesrams', 'baseball', 'mlb', 'fantasybaseball', 'nba',
                      'collegebasketball', 'nbastreams', 'fantasybball', 'warriors', 'lakers', 'bostonceltics',
                      'torontoraptors', 'sixers', 'chicagobulls', 'skateboarding', 'snowboarding', 'longboarding',
                      'formula1', 'Nascar', 'MMA', 'squaredcircle', 'theocho', 'ufc', 'boxing', 'wwe', 'MMAStreams',
                      'hockey', 'nhl', 'nhlstreams', 'leafs', 'olympics', 'apocalympics2016', 'soccer', 'worldcup',
                      'Bundesliga', 'futbol', 'soccerstreams', 'MLS', 'fantasypl', 'gunners', 'reddevils',
                      'LiverpoolFC', 'chelseafc', 'Television', 'marvelstudios', 'japanesegameshows', 'shield',
                      'cordcutters', 'offlinetv', 'tvdetails', 'GameOfThrones', 'BreakingBad', 'thewalkingdead',
                      'community', 'arresteddevelopment', 'topgear', 'StarTrek', 'HIMYM', 'firefly', 'PandR',
                      'Sherlock', 'DunderMifflin', 'BetterCallSaul', 'TrueDetective', 'houseofcards', 'MakingaMurderer',
                      'FlashTV', 'trailerparkboys', 'mrrobot', 'siliconvalleyhbo', 'strangerthings', 'supernatural',
                      'thegrandtour', 'AmericanHorrorStory', 'rupaulsdragrace', 'westworld', 'blackmirror',
                      'FilthyFrank', 'orangeisthenewblack', 'twinpeaks', 'bigbrother', 'brooklynninenine', 'scrubs',
                      'howyoudoin', '30rock', 'lifeisstrange', 'survivor', 'riverdale', 'letterkenny', 'Pokemon',
                      'AdventureTime', 'futurama', 'TheLastAirbender', 'ArcherFX', 'southpark', 'TheSimpsons',
                      'mylittlepony', 'rickandmorty', 'naruto', 'stevenuniverse', 'onepunchman', 'BobsBurgers',
                      'BoJackHorseman', 'gravityfalls', 'familyguy', 'kingofthehill', 'spongebob', 'dbz',
                      'DBZDokkanBattle', 'dragonballfighterz', 'doctorwho', 'gallifrey', 'IASIP', 'the_dennis',
                      'seinfeld', 'redditwritesseinfeld', 'seinfeldgifs', 'NetflixBestOf', 'Netflix', 'bestofnetflix',
                      'DIY', 'cosplay', 'woodworking', 'somethingimade', 'architecture', 'CoolGuides', 'WorldBuilding',
                      'ifyoulikeblank', 'DiWHY', 'knitting', 'sewing', 'modelmakers', 'crochet', 'ProtectAndServe',
                      'RTLSDR', 'digitalnomad', 'FastWorkers', 'accounting', 'preppers', 'redneckengineering',
                      'crossstitch', 'dumpsterdiving', 'gunpla', 'urbanplanning', 'cubers', 'blacksmith', 'toptalent',
                      'slavelabour', 'aquariums', 'plantedtank', 'art', 'Drawing', 'crafts', 'alternativeart',
                      'sketchdaily', 'artporn', 'glitch_art', 'coloringcorruptions', 'restofthefuckingowl',
                      'DisneyVacation', 'illustration', 'Writing', 'writingprompts', 'screenwriting', 'fountainpens',
                      'calligraphy', 'handwriting', 'twosentencehorror', 'brandnewsentence', 'cars', 'motorcycles',
                      'carporn', 'justrolledintotheshop', 'idiotsincars', 'Shitty_Car_Mods', 'autos', 'roadcam',
                      'AutoDetailing', 'awesomecarmods', 'projectcar', 'cartalk', 'tiresaretheenemy', 'roadtrip',
                      'convenientcop', 'dashcamgifs', 'subaru', 'teslamotors', 'bmw', 'jeep', 'CrappyDesign',
                      'web_design', 'graphic_design', 'design', 'designporn', 'InteriorDesign', 'ATBGE',
                      'dontdeadopeninside', 'assholedesign', 'keming', 'logodesign', 'tombstoning', 'dangerousdesign',
                      'actlikeyoubelong', 'irlsmurfing', 'MilitaryPorn', 'military', 'combatfootage', 'militarygfys',
                      'army', 'warshipporn', 'justbootthings', 'guns', 'gunporn', 'gundeals', 'ar15', 'firearms', 'ccw',
                      'airsoft', 'Jobs', 'forhire', 'cscareerquestions', 'workonline', 'guitar', 'WeAreTheMusicMakers',
                      'edmproduction', 'piano', 'ableton', 'drums', 'FL_Studio', 'urbanexploration', 'survival',
                      'backpacking', 'camping', 'homestead', 'MTB', 'outdoors', 'wildernessbackpacking', 'campinggear',
                      'bushcraft', 'gardening', 'indoorgarden', 'campingandhiking', 'hiking', 'ultralight',
                      'photography', 'itookapicture', 'Filmmakers', 'astrophotography', 'analog', 'photocritique',
                      'postprocessing', 'aviation', 'flying', 'sysadmin', 'engineering', 'compsci', 'webdev',
                      'programmerhumor', 'graphic_design', 'mechanicalkeyboards', 'reverseengineering',
                      'itsaunixsystem', 'plex', 'multicopter', 'programminghorror', 'dailyprogrammer', 'coding',
                      'python', 'java', 'cpp', 'security', 'buildapc', 'buildapcsales', 'buildapcforme',
                      'talesfromtechsupport', 'techsupportgore', 'techsupport', 'softwaregore', 'iiiiiiitttttttttttt',
                      'watches', 'lockpicking', 'knives', 'specializedtools', 'knifeclub', 'travel', 'solotravel',
                      'japantravel', 'shoestring', 'LifeProTips', 'lifehacks', 'geek', 'EDC', 'simpleliving',
                      'tinyhouses', 'rainmeter', 'vandwellers', 'UnethicalLifeProTips', 'vagabond',
                      'illegallifeprotips', 'malelifestyle', 'malelivingspace', 'TheGirlSurvivalGuide',
                      'homeimprovement', 'homelab', 'homeautomation', 'battlestations', 'hometheater', 'teenagers',
                      'introvert', 'ADHD', 'totallynotrobots', 'polyamory', 'teachers', 'aliensamongus',
                      'neverbrokeabone', 'bipolar', 'beards', 'vegan', 'swoleacceptance', 'tall', 'lgbt', 'gaybros',
                      'actuallesbians', 'gaymers', 'bisexual', 'askgaybros', 'ainbow', 'gay', 'gay_irl',
                      'asktransgender', 'transgender', 'parenting', 'daddit', 'babybumps', 'drunk', 'scotch',
                      'stopdrinking', 'cocktails', 'wine', 'bourbon', 'whiskey', 'beer', 'homebrewing', 'showerbeer',
                      'beerporn', 'trees', 'marijuana', 'microgrowery', 'eldertrees', 'see', 'leaves', 'weed',
                      'weedstocks', 'cannabis', 'drugs', 'electronic_cigarette', 'stonerengineering', 'Nootropics',
                      'LSD', 'vaporents', 'Vaping', 'stopsmoking', 'shrooms', 'dmt', 'GetMotivated', 'health',
                      'ZenHabits', 'motivation', 'LucidDreaming', 'meditation', 'Psychonaut', 'mentalhealth',
                      'Fitness!', 'Fitness', 'xxfitness', 'fitmeals', 'paleo', 'nutrition', 'vegetarian', 'leangains',
                      'HealthyFood', 'intermittentfasting', 'fasting', 'keto', 'ketorecipes', 'ketogains', 'bicycling',
                      'yoga', 'skateboarding', 'climbing', 'backpacking', 'bjj', 'skiing', 'crossfit', 'bodybuilding',
                      'WeightRoom', 'powerlifting', 'running', 'c25k', 'Medicine', 'Coronavirus', 'COVID19', 'loseit',
                      'bodyweightfitness', 'gainit', 'swoleacceptance', 'flexibility', 'progresspics', 'brogress',
                      'makeupaddiction', 'SkincareAddiction', 'beards', 'wicked_edge', 'RedditLaqueristas',
                      'AsianBeauty', 'piercing', 'FancyFollicles', 'malehairadvice', 'curlyhair', 'tattoos',
                      'badtattoos', 'tattoo', 'malefashionadvice', 'frugalmalefashion', 'femalefashionadvice',
                      'thriftstorehauls', 'fashion', 'streetwear', 'malefashion', 'supremeclothing', 'FashionReps',
                      'designerreps', 'sneakers', 'repsneakers', 'goodyearwelt', 'food', 'FoodPorn', 'foodhacks',
                      'shittyfoodporn', 'eatsandwiches', 'nutrition', 'mealtimevideos', 'WeWantPlates',
                      'forbiddensnacks', 'seriouseats', 'spicy', 'cooking', 'slowcooking', 'askculinary', 'baking',
                      'mealprepsunday', 'breadit', 'cookingforbeginners', 'smoking', 'castiron', 'instantpot',
                      'sousvide', 'EatCheapAndHealthy', 'fitmeals', 'budgetfood', 'ketorecipes', 'vegan',
                      '1200isplenty', 'Cheap_Meals', 'HealthyFood', 'veganrecipes', 'intermittentfasting', 'fasting',
                      'coffee', 'tea', 'recipes', 'gifrecipes', 'veganrecipes', 'pizza', 'grilledcheese', 'ramen',
                      'bbq', 'sushi', 'PersonalFinance', 'Entrepreneur', 'beermoney', 'startups', 'finance', 'economy',
                      'financialindependence', 'apphookup', 'churning', 'realestate', 'flipping', 'antimlm', 'ripple',
                      'Iota', 'stellar', 'personalfinancecanada', 'investing', 'wallstreetbets', 'millionairemakers',
                      'weedstocks', 'options', 'pennystocks', 'frugal', 'EatCheapAndHealthy', 'frugalmalefashion',
                      'budgetfood', 'cheap_meals', 'Frugal_Jerk', 'povertyfinance', 'shutupandtakemymoney',
                      'BuyItForLife', 'crappyoffbrands', 'shouldibuythisgame', 'Anticonsumption', 'sbubby', 'Wellworn',
                      'ineeeedit', 'didntknowiwantedthat', 'Bitcoin', 'dogecoin', 'CryptoCurrency', 'ethereum',
                      'ethtrade', 'litecoin', 'btc', 'garlicoin', 'cardano', 'Vechain', 'Psychonaut', 'Buddhism',
                      'Stoicism', 'occult', 'atheism', 'trueatheism', 'Christianity', 'dankchristianmemes', 'exmormon',
                      'Catholicism', 'philosophy', 'askphilosophy', 'socialskills', 'socialengineering',
                      'weddingplanning', 'Parenting', 'childfree', 'raisedbynarcissists', 'incest', 'daddit',
                      'justnomil', 'justnofamily', 'relationships', 'relationship_advice', 'dating_advice', 'breakups',
                      'dating', 'Tinder', 'OKCupid', 'r4r', 'dirtyr4r', 'longdistance', 'sex', 'seduction', 'nofap',
                      'deadbedrooms', 'polyamory', 'GetMotivated', 'QuotesPorn', 'getdisciplined', 'happy',
                      'productivity', 'DecidingToBeBetter', 'mademesmile', 'selfimprovement', 'iwantout',
                      'humansbeingbros', 'happycrowds', 'sportsarefun', 'GetStudying', 'motivation',
                      'gatesopencomeonin', 'technology,', 'technology', 'internetisbeautiful', 'futurology',
                      'pcmasterrace', 'buildapc', 'talesfromtechsupport', 'netsec', 'gamedev', 'design', 'engineering',
                      'jailbreak', 'compsci', 'tech', 'hacking', 'imaginarytechnology', 'privacy', 'torrents',
                      'networking', 'infographics', 'piracy', 'EngineeringPorn', 'cableporn', 'simulated', 'onions',
                      'unixporn', 'crackwatch', 'php', 'aboringdystopia', 'virtualreality', 'opensource', '3Dprinting',
                      'functionalprint', 'nintendo', 'spacex', 'nasa', 'amd', 'nvidia', 'photoshop', 'firefox',
                      'Android', 'AndroidApps', 'AndroidGaming', 'AndroidDev', 'AndroidThemes', 'oneplus', 'apple',
                      'iphone', 'mac', 'ipad', 'applewatch', 'gadgets', 'raspberry_pi', 'electronics', 'arduino',
                      'trackers', 'gopro', 'blender', 'amazonecho', 'RetroPie', 'hardware', 'hardwareswap',
                      'Addons4Kodi', 'kodi', 'google', 'chromecast', 'googlepixel', 'googlehome', 'linux',
                      'linux_gaming', 'linux4noobs', 'linuxmasterrace', 'archlinux', 'Windows10', 'windows', 'excel',
                      'surface', 'microsoft', 'dataisbeautiful', 'DataHoarder', 'datascience', 'Bitcoin', 'dogecoin',
                      'CryptoCurrency', 'ethereum', 'ethtrader', 'btc', 'litecoin', 'bitcoinmarkets', 'cryptomarkets',
                      'monero', 'neo', 'programming', 'learnprogramming', 'python', 'java', 'javascript', 'learnpython',
                      'excel', 'unity3d', 'reactjs', 'audiophile', 'headphones', 'audioengineering', 'funny', 'humor',
                      'contagiouslaughter', 'standupcomedy', 'ProgrammerHumor', 'prematurecelebration',
                      'ChildrenFallingOver', 'dadreflexes', 'kenm', 'politicalhumor', 'accidentalcomedy', 'funnyandsad',
                      'kidsarefuckingstupid', 'notkenm', 'suspiciouslyspecific', 'oddlyspecific', 'rimjob_steve',
                      'dark_humor', 'stepdadreflexes', 'congratslikeimfive', 'darkhumorandmemes', 'ComedyCemetery',
                      'comedyheaven', 'comedynecromancy', 'comedyhomicide', 'comedynecrophilia', 'Jokes', 'dadjokes',
                      'standupshots', 'punny', 'antijokes', 'meanjokes', '3amjokes', 'puns', 'WordAvalanches',
                      'darkjokes', 'AnimalReddits.', 'AnimalsBeingJerks', 'AnimalsBeingBros', 'AnimalPorn',
                      'AnimalsBeingDerps', 'likeus', 'stoppedworking', 'hitmanimals', 'animaltextgifs',
                      'BeforeNAfterAdoption', 'sneks', 'TsundereSharks', 'whatsthisbug', 'HybridAnimals', 'zoomies',
                      'brushybrushy', 'bigboye', 'curledfeetsies', 'mlem', 'Floof', 'shittyanimalfacts',
                      'animalsthatlovemagic', 'spiderbro', 'properanimalnames', 'reverseanimalrescue',
                      'animalsdoingstuff', 'sploot', 'birdswitharms', 'superbowl', 'birbs', 'partyparrot',
                      'birdsbeingdicks', 'emuwarflashbacks', 'birdsarentreal', 'babyelephantgifs', 'sloths', 'foxes',
                      'trashpandas', 'happycowgifs', 'rabbits', 'goatparkour', 'bearsdoinghumanthings', 'cats',
                      'startledcats', 'catpictures', 'catsstandingup', 'catpranks', 'meow_irl', 'holdmycatnip',
                      'catslaps', 'thecatdimension', 'babybigcatgifs', 'catloaf', 'thisismylifemeow', 'cattaps',
                      'teefies', 'tuckedinkitties', 'catsareassholes', 'catsisuottatfo', 'stuffoncats', 'bigcatgifs',
                      'jellybeantoes', 'catsareliquid', 'catgifs', 'blackcats', 'supermodelcats', 'chonkers',
                      'tightpussy', 'catswithjobs', 'catswhoyell', 'whatswrongwithyourcat', 'illegallysmolcats', 'dogs',
                      'dogpictures', 'dogtraining', 'woof_irl', 'WhatsWrongWithYourDog', 'dogberg', 'dogswithjobs',
                      'masterreturns', 'barkour', 'blop', 'puppysmiles', 'puppies', 'petthedamndog', 'corgi',
                      'Pitbulls', 'goldenretrievers', 'incorgnito', 'babycorgis', 'conspiracy', 'skeptic',
                      'karmaconspiracy', 'UFOs', 'conspiratard', 'empiredidnothingwrong', 'scp', 'birdsarentreal',
                      'conspiracytheories', 'cringepics', 'cringe', 'instant_regret', 'blunderyears', 'facepalm',
                      'fatlogic', 'publicfreakout', 'actualpublicfreakouts', 'lewronggeneration', 'fellowkids',
                      'sadcringe', 'corporatefacepalm', '4PanelCringe', 'amibeingdetained', 'instantbarbarians',
                      'watchpeopledieinside', 'technicallythetruth', 'accidentalracism', 'engrish', 'wokekids',
                      'masterhacker', 'cringetopia', 'holup', 'agedlikemilk', 'tiktokcringe', 'facepalm',
                      'quityourbullshit', 'thathappened', 'delusionalartists', 'oopsdidntmeanto', 'beholdthemasterrace',
                      'murderedbywords', 'ihavesex', 'woooosh', 'badfaketexts', 'boneappletea', 'atetheonion',
                      'iamatotalpieceofshit', 'suicidebywords', 'kamikazebywords', 'wowthanksimcured',
                      'topmindsofreddit', 'lostredditors', 'dontyouknowwhoiam', 'NobodyAsked', 'dontfundme',
                      'nothingeverhappens', 'vaxxhappened', 'goodfaketexts', 'delusionalcraigslist', 'suspiciousquotes',
                      'facingtheirparenting', 'ihadastroke', 'untrustworthypoptarts', 'phonesarebad', 'rareinsults',
                      'clevercomebacks', 'fuckyoukaren', 'uselessredcircle', 'leopardsatemyface',
                      'confidentlyincorrect', 'niceguys', 'mallninjashit', 'ChoosingBeggars', 'gatekeeping',
                      'creepyasterisks', 'inceltears', 'humblebrag', 'nothowdrugswork', 'whiteknighting',
                      'neckbeardrpg', 'virginsvschad', 'nicegirls', 'notliketheothergirls', 'notlikeothergirls',
                      'entitledbitch', 'iamverysmart', 'iamverybadass', 'iamveryrandom', 'imveryedgy',
                      'justneckbeardthings', 'neckbeardnests', 'entitledparents', 'insaneparents', 'shitmomgroupssay',
                      'aww', 'cats', 'animalsbeingjerks', 'animalsbeingbros', 'Awwducational', 'dogs', 'corgi',
                      'thisismylifenow', 'blep', 'eyebeach', 'tippytaps', 'awww', 'babycorgis', 'WTF',
                      'DeepIntoYouTube', 'fifthworldproblems', 'awwwtf', 'wellthatsucks', 'streetfights',
                      'yesyesyesyesno', 'wtfstockphotos', 'yesyesyesno', 'maybemaybemaybe', 'oddlyterrifying',
                      'thatlookedexpensive', 'wtfgaragesale', 'Whatthefuckgetitoffme', 'imsorryjon',
                      'mildlyinfuriating', 'crappydesign', 'rage', 'Bad_Cop_No_Donut', 'gifsthatendtoosoon',
                      'peoplebeingjerks', 'casualchildabuse', 'fuckthesepeople', 'makemesuffer', 'cursedimages',
                      'cursedcomments', 'tihi', 'blursedimages', 'cursed_images', 'blessedimages',
                      'imgoingtohellforthis', 'toosoon', 'trashy', 'awfuleyebrows', 'awfuleverything', '13or30',
                      'ghettoglamourshots', 'peopleofwalmart', 'hittablefaces', 'punchablefaces', 'botchedsurgeries',
                      'subwaycreatures', 'nosleep', 'morbidreality', 'whatcouldgowrong', 'Glitch_in_the_Matrix',
                      'Paranormal', 'nononono', 'horror', 'shortscarystories', 'lastimages', 'peoplefuckingdying',
                      'serialkillers', 'WhyWereTheyFilming', 'WinStupidPrizes', 'scarysigns', 'ghosts', 'crimescene',
                      'creepy', 'creepypasta', 'creepysigns', 'megalophobia', 'creepyencounters', 'ImaginaryMonsters',
                      'ImaginaryLeviathans', 'ImaginaryMindscapes', 'imaginarycharacters', 'imaginarylandscapes',
                      'imaginarymaps', 'SympatheticMonsters', 'imaginarywesteros', 'imaginarysliceoflife',
                      'thalassophobia', 'TheDepthsBelow', 'submechanophobia', 'freebies', 'fullmoviesonyoutube',
                      'efreebies', 'randomactsofgaming', 'freeEbooks', 'fullmoviesonvimeo', 'freegamesonsteam',
                      'googleplaydeals', 'megalinks', 'opendirectories', 'Random_Acts_Of_Pizza', 'coupons',
                      'dealsreddit', 'freegamefindings', 'deals', 'assistance', 'free', 'MaleFashionAdvice',
                      'everymanshouldknow', 'askmen', 'frugalmalefashion', 'MensRights', 'malelifestyle',
                      'trollychromosome', 'malelivingspace', 'malehairadvice', 'malefashion', 'bigdickproblems',
                      'mgtow', 'askmenover30', 'TwoXChromosomes', 'askwomen', 'LadyBoners', 'TrollXChromosomes',
                      'femalefashionadvice', 'xxfitness', 'TheGirlSurvivalGuide', 'abrathatfits', 'badwomensanatomy',
                      'nothowgirlswork', 'menwritingwomen', 'LocationReddits.', 'MapPorn', 'polandball', 'vexillology',
                      'SouthAfrica', 'europe', 'ireland', 'thenetherlands', 'denmark', 'italy', 'norge', 'polska',
                      'suomi', 'romania', 'belgium', 'scotland', 'austria', 'france', 'french', 'de', 'germany',
                      'german', 'ANormalDayInRussia', 'youseecomrade', 'gtaorrussia', 'sweden', 'SWARJE',
                      'swedishproblems', 'intresseklubben', 'svenskpolitik', 'spop', 'Allsvenskan', 'unitedkingdom',
                      'britishproblems', 'london', 'ukpolitics', 'casualuk', 'canada', 'toronto', 'vancouver',
                      'canadapolitics', 'calgary', 'personalfinancecanada', 'mexico', 'MURICA', 'nyc', 'chicago',
                      'portland', 'boston', 'atlanta', 'washingtondc', 'philadelphia', 'newjersey', 'minnesota',
                      'michigan', 'losangeles', 'sanfrancisco', 'bayarea', 'california', 'sandiego', 'disneyland',
                      'denver', 'colorado', 'floridaman', 'waltdisneyworld', 'austin', 'houston', 'texas', 'dallas',
                      'seattle', 'SeattleWA', 'australia', 'newzealand', 'melbourne', 'sydney', 'Philippines', 'india',
                      'singapore', 'china', 'hongkong', 'japan', 'japanpics', 'japantravel', 'kpop', 'pyongyang',
                      'korea', 'brasil', 'argentina', 'ithadtobebrazil', 'OutOfTheLoop', 'nocontext', 'tldr',
                      'Enhancement', 'SecretSanta', 'MuseumOfReddit', 'theoryofreddit', 'threadkillers',
                      'evenwithcontext', 'beetlejuicing', 'redditinreddit', 'announcements', 'blog', 'beta', 'help',
                      'place', 'sequence', 'thebutton', 'circleoftrust', 'baconreader', 'alienblue', 'baconit',
                      'redditsync', 'relayforreddit', 'apolloapp', 'redditmobile', 'Circlejerk', 'DiWHY', 'frugal_jerk',
                      'moviescirclejerk', 'SubredditDrama', 'drama', 'hobbydrama', 'rbi', 'ShitRedditSays',
                      'karmaconspiracy', 'undelete', 'jesuschristreddit', 'karmacourt', 'titlegore', 'ShitAmericansSay',
                      'againsthatesubreddits', 'bestof', 'DepthHub', 'BestOfReports', 'bestoflegaladvice', 'punpatrol',
                      'redditsings', 'subredditoftheday', 'wowthissubexists', 'newreddits', 'ofcoursethatsathing',
                      'findareddit', 'modnews', 'redditrequest', 'subredditsimulator', 'subredditsimmeta', 'TrueReddit',
                      'awesome', 'TipOfMyTongue', 'TipOfMyPenis', 'woahdude', 'frisson', 'asmr', 'VaporwaveAesthetics',
                      'glitchinthematrix', 'earthporn', 'hardcoreaww', 'hitmanimals', 'natureisfuckinglit', 'heavyseas',
                      'marijuanaenthusiasts', 'succulents', 'mycology', 'bonsai', 'TreesSuckingOnThings', 'houseplants',
                      'natureismetal', 'Natureisbrutal', 'naturewasmetal', 'weathergifs', 'tropicalweather',
                      'worldnews', 'news', 'nottheonion', 'UpliftingNews', 'offbeat', 'gamernews', 'floridaman',
                      'energy', 'syriancivilwar', 'truecrime', 'TheOnion', 'AteTheOnion', 'OldSchoolCool',
                      'TheWayWeWere', 'nostalgia', 'vinyl', 'forwardsfromgrandma', 'oldphotosinreallife',
                      'firstworldanarchists', 'wheredidthesodago', 'unexpectedthuglife', 'youdontsurf',
                      'montageparodies', 'outside', 'OSHA', 'hailcorporate', 'im14andthisisdeep', 'bollywoodrealism',
                      'AccidentalRenaissance', 'maliciouscompliance', 'fakehistoryporn', 'coaxedintoasnafu',
                      'irleastereggs', 'sfwpornnetwork.', 'EarthPorn', 'HistoryPorn', 'FoodPorn', 'JusticePorn',
                      'AbandonedPorn', 'SpacePorn', 'RoomPorn', 'QuotesPorn', 'MapPorn', 'CityPorn', 'carporn',
                      'humanporn', 'penmanshipporn', 'militaryporn', 'DesignPorn', 'ThingsCutInHalfPorn',
                      'ArchitecturePorn', 'ExposurePorn', 'futureporn', 'adrenalineporn', 'waterporn', 'machineporn',
                      'animalporn', 'movieposterporn', 'illusionporn', 'destructionporn', 'adporn', 'artefactporn',
                      'gunporn', 'skyporn', 'powerwashingporn', 'ArtPorn', 'InfrastructurePorn', 'VillagePorn',
                      'shockwaveporn', 'productporn', 'macroporn', 'cabinporn', 'houseporn', 'mineralporn', 'microporn',
                      'shittyaskscience', 'shittyfoodporn', 'shittyreactiongifs', 'crappydesign', 'Shitty_Car_Mods',
                      'shittyadvice', 'shittyrobots', 'ShittyLifeProTips', 'shittykickstarters', 'shittyanimalfacts',
                      'shitpost', 'shittymoviedetails', 'unexpected', 'UnexpectedThugLife', 'misleadingthumbnails',
                      'unexpectedjihad', 'slygifs', 'blackmagicfuckery', 'unexpectedhogwarts', 'UnexpectedMulaney',
                      'AbandonedPorn', 'OddlySatisfying', 'RoomPorn', 'nonononoyes', 'minimalism', 'CityPorn',
                      'penmanshipporn', 'Cinemagraphs', 'ImaginaryLandscapes', 'eyebleach', 'DesignPorn',
                      'perfectloops', 'perfectfit', 'humansbeingbros', 'powerwashingporn', 'nevertellmetheodds',
                      'typography', 'cozyplaces', 'breathinginformation', 'desirepath', 'tiltshift', 'mostbeautiful',
                      'AmateurRoomPorn', 'slygifs', 'raining', 'AccidentalWesAnderson', 'unstirredpaint', 'handwriting',
                      'thatpeelingfeeling', 'gtage', 'satisfyingasfuck', 'holdmybeer', 'holdmyjuicebox', 'holdmyfries',
                      'holdmybeaker', 'holdmycosmo', 'holdmycatnip', 'holdmyredbull', 'holdmyfeedingtube', 'fiftyfifty',
                      'firstworldproblems', 'idiotsfightingthings', 'whatsinthisthing', 'notinteresting',
                      'fifthworldpics', 'drunkorakid', 'pussypassdenied', 'UNBGBBIIVCHIDCTIICBG', 'Justfuckmyshitup',
                      'BestOfStreamingVideo', 'CatastrophicFailure', 'evilbuildings', 'urbanhell', 'justiceserved',
                      'mypeopleneedme', 'notmyjob', 'onejob', 'sweatypalms', 'therewasanattempt', 'bitchimabus',
                      'greendawn', 'thingsforants', 'youseeingthisshit', 'hmmm', 'hadtohurt', 'MandelaEffect',
                      'mildlypenis', 'redditdayof', 'instantkarma', '2healthbars', 'collapse', 'slavs_squatting',
                      'confusing_perspective', 'the_pack', 'unpopularopinion', 'okbuddyretard', 'nextfuckinglevel',
                      'ooer', 'happycryingdads', 'FullScorpion', 'instantregret', 'MildlyVandalised',
                      'watchpeoplesurvive', 'tendies', 'dontputyourdickinthat', 'whatintarnation', 'tworedditorsonecup',
                      'ExpandDong', 'wackytictacs', 'halloween', 'whatcouldgoright', 'hmmmgifs', 'bizarrebuildings',
                      'inclusiveor', 'lostgeneration', 'kurzgesagt', 'boop', 'fightporn', 'tooktoomuch',
                      'humansaremetal', 'theyknew', 'fbiopenup', 'fuckyouinparticular', 'idiotsnearlydying',
                      'AAAAAAAAAAAAAAAAA', 'chaoticgood', 'prisonwallet', 'mindcrack', 'twitchplayspokemon',
                      'battlefield3', 'punchablefaces', 'csgobetting', 'historicalwhatif']
used_subreddit_list = large_subreddit_list_1 + large_subreddit_list_2 + middle_subreddit_list_1
subreddit_list = [sub for sub in list_of_subreddits if sub not in used_subreddit_list]

random.seed(4)
random.shuffle(subreddit_list)
sampled_subreddit_list = subreddit_list[400:500]

# 49
for count, subreddit_name in enumerate(sampled_subreddit_list):
    if count >= 97:
        print(count, subreddit_name)
        reddit.subreddit(subreddit_name).message(subject, content.format(subreddit_name))
